<?php
namespace com\plugish\Tests;

use Brain\Monkey;
use PHPUnit\Framework\TestCase as PHPUnitTestCase;

class TestCase extends PHPunitTestCase {
	protected function setUp(): void {
		parent::setUp(); // TODO: Change the autogenerated stub
		Monkey\setUp();

		$this->setOutputCallback( function() {} );
	}

	protected function tearDown(): void {
		Monkey\tearDown();
		parent::tearDown(); // TODO: Change the autogenerated stub
	}
}